name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android environment
      uses: android-actions/setup-android@v3

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/client
        chmod 755 gradlew
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: ${{ github.workspace }}/client/app/build/outputs/apk/release/
